# Generated by Django 2.2.6 on 2019-10-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
        ),
    ]
